# 모두를 위한 딥러닝 시즌2 with Pytorch
- 오늘은 기본적인 Tensor 연산에 대해서 공부해보자.


In [1]:
import numpy as np
import torch

# Numpy 1차원

In [10]:
t = np.array([0,1,2,3,4,5,6])

In [13]:
print('Rank of t', t.ndim)
print('shape of t', t.shape)

Rank of t 1
shape of t (7,)


# Numpy 2차원

In [14]:
t = np.array([[0,1,2],
              [3,4,5],
              [6,7,8]])

In [15]:
print('Rank of t', t.ndim)
print('shape of t', t.shape)

Rank of t 2
shape of t (3, 3)


# Tensor 1차원

In [20]:
t = torch.FloatTensor([i for i in range(1,7)])
print(t)

tensor([1., 2., 3., 4., 5., 6.])


In [28]:
print("dim", t.dim())
print("shape",t.shape)
print("size", t.size())
print(t[:len(t)])

dim 1
shape torch.Size([6])
size torch.Size([6])
tensor([1., 2., 3., 4., 5., 6.])


# Tensor 2차원

In [35]:
t = torch.FloatTensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [37]:
print("dim", t.dim())
print("shape",t.shape)
print("size", t.size())
print(t[:,:-1])

dim 2
shape torch.Size([3, 3])
size torch.Size([3, 3])
tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])


# Broadcasting
- 행렬의 연산과 관해서, 크기가 동일해야 한다는 수학적인 규칙이 존재한다.
- 이때, Broadcast 기능을 이용해서 자동적으로 크기를 맞출 수 있다.
- 자동으로 크기를 맞추기 때문에, 원하는 shape로 계산이 되었는지 유의해야 한다.

In [41]:
m1 = torch.FloatTensor([[1],[2]]) # -> [[1,2],[1,2]] 
m2 = torch.FloatTensor([[1,2],
                      [3,4]])

m1 + m2

tensor([[2., 3.],
        [5., 6.]])

# mul vs matmul
- mul은 해당하는 요소들끼리 곱하는 것을 의미함
- matmul은 흔히 우리가 알고 있는 행렬곱을 의미함

In [45]:
# mul
m1 = torch.FloatTensor([[1,2],
                       [3,4]])
m2 = torch.FloatTensor([[1],[2]]) # 2 x 1 -> 2 x 2의 broadcasting이 일어남.

print(m1.mul(m2))


tensor([[1., 2.],
        [6., 8.]])


In [47]:
# matmul
print(m1.matmul(m2))

tensor([[ 5.],
        [11.]])


# Mean
- 기본적으로 float type에 대해서만 사용 가능하다.

In [50]:
t = torch.FloatTensor([1,2])
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as ex:
    print(ex)

Can only calculate the mean of floating types. Got Long instead.


# Dim에 따른 Mean

In [56]:
t = torch.FloatTensor([[1,2],[3,4]]) # 2 x 2
print(t.mean())
print(t.mean(dim = 0)) # 2 x 2 -> 1 x 2로 줄여버리기. (dim = 0을 1로 줄이기)
print(t.mean(dim = 1))  # 2 x 2 -> 2 x 1로 줄여버리기. (dim = 1을 1로 줄이기)
print(t.mean(dim = -1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


# Dim에 따른 Sum

In [61]:
t = torch.FloatTensor([[1,2,3],[3,4,5]])
print(t.sum())
print(t.sum(dim = 0)) # 4 6 8
print(t.sum(dim = 1)) # 6 12
print(t.sum(dim = -1)) # 6 12

tensor(18.)
tensor([4., 6., 8.])
tensor([ 6., 12.])
tensor([ 6., 12.])


# Max and Argmax

- value: t.max(dim = 차원)[0] 
- index: t.max(dim = 차원)[1] => argmax라고 지칭한다. (index of element with maximum value.)

In [70]:
t = torch.FloatTensor([[3,1],[2,4]])
print(t.max())
print(t.max(dim = 0)) # 1 x 2
print(t.max(dim = 1)) # 2 x 1


tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([0, 1]))
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([0, 1]))


In [72]:
print(t.max(dim = 0))
print(t.max(dim = 1))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([0, 1]))
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([0, 1]))


# 두번째 강의

# View
- Reshape을 목표로 만들어짐
- -1은 나머지 수를 의미함

In [76]:
t = np.array([[[0,1,2],
               [3,4,5]],
               
               [[6,7,8],
                [9,10,11]]
                         ])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [78]:
# 나머지*3
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)


tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [80]:
# 나머지*3
print(ft.view([2,-1]))
print(ft.view([2,-1]).shape)


tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])
torch.Size([2, 6])


In [81]:
# 나머지*3
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)


tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


# Squeeze
- 영어로 쥐어짜다를 의미함.
- 1인 차원을 없애줌
- Dim을 반드시 명시할 필요가 없음.

In [83]:
ft = torch.FloatTensor([[i] for i in range(3)])
print(ft)
print(ft.shape)


tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [85]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


# Unsqueeze

In [86]:
ft = torch.Tensor([0,1,2])
print(ft.shape) # (3,)

torch.Size([3])


In [87]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [88]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [89]:
print(ft.view(1,-1)) # 1 * 3
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


# Type Casting

In [90]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [91]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [93]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [94]:
print(bt.long()) # integer를 의미하나보다.
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


# Concatenate
- 어느 방향으로 붙이는 지가 중요하다.

In [97]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [99]:
print(torch.cat([x,y], dim = 0)) # dim 0방향으로 붙인다.

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [100]:
print(torch.cat([x,y], dim = 1)) # dim가 1인 곳에 변화를 주겠다.

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# Stacking 
- 쌓는다고 생각하면 된다.

In [109]:
x = torch.FloatTensor([1,4]) 
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [110]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim=1)) # dim가 1인 곳에 변화를 주겠다.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [113]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))
print(torch.stack([x,y,z],dim = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [108]:
# 연습
x = torch.FloatTensor([1,2,3]) # 
y = torch.FloatTensor([4,5,6]) 

print(torch.stack([x,y], dim = 1)) #  ? * 2
print(torch.stack([x,y], dim = 0)) #  2 * ?

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


# ones and zeros

In [114]:
x = torch.FloatTensor([[0,1,2],
                       [2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [115]:
'''
같은 device에서 나오는 게 중요:
GPU면 GPU, CPU도 여러개만 같은 걸로 수행
'''
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# In-place Operation
- 임의의 메모리에 저장해주는 일이 있는데, 해당 메모리에 저장해주는 것으로 _(under bar)를 사용한다.

In [116]:
x = torch.FloatTensor([[1,2],
                       [3,4]])


In [117]:
print(x.mul(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [118]:
print(x.mul_(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


# 느낀점: Tensor 기본연산에 대한 이해를 가질 수 있었다.
기본적으로 Shape을 이해하는 것이 너무 중요하고, dim관련 연산에서 모든 걸 기억하고 있을 수는 없지만 해당 dim에 변화를 주겠다는 생각으로 이해하면 되겠다.

In [149]:
x.reshape(4,-1)
x.view(4,-1)
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.]])

In [144]:
y = torch.transpose(y,0,1) # 1*2
torch.cat([x,y],dim = 0)

tensor([[2., 4.],
        [6., 8.],
        [2., 5.]])

In [146]:
y = torch.transpose(y,0,1) # 2*1
torch.cat([x,y],dim = 1)

tensor([[2., 4., 2.],
        [6., 8., 5.]])