In [3]:
import six.moves.cPickle as pickle
import gzip
import os
import numpy as np
import scipy.misc

def load_data(dataset):
    ''' Loads the dataset

    :type dataset: string
    :param dataset: the path to the dataset (here MNIST)
    
    copied from http://deeplearning.net/ and revised by hchoi
    '''

    # Download the MNIST dataset if it is not present
    data_dir, data_file = os.path.split(dataset)
    if data_dir == "" and not os.path.isfile(dataset):
        # Check if dataset is in the data directory.
        new_path = os.path.join(
            os.path.split(__file__)[0],
            dataset
        )
        if os.path.isfile(new_path) or data_file == 'mnist.pkl.gz':
            dataset = new_path

    if (not os.path.isfile(dataset)) and data_file == 'mnist.pkl.gz':
        from six.moves import urllib
        origin = (
            'http://www.iro.umontreal.ca/~lisa/deep/data/mnist/mnist.pkl.gz'
        )
        print('Downloading data from %s' % origin)
        urllib.request.urlretrieve(origin, dataset)

    print('... loading data')

    # Load the dataset
    with gzip.open(dataset, 'rb') as f:
        try:
            train_set, valid_set, test_set = pickle.load(f, encoding='latin1')
        except:
            train_set, valid_set, test_set = pickle.load(f)
    # train_set, valid_set, test_set format: tuple(input, target)
    # input is a numpy.ndarray of 2 dimensions (a matrix)
    # where each row corresponds to an example. target is a
    # numpy.ndarray of 1 dimension (vector) that has the same length as
    # the number of rows in the input. It should give the target
    # to the example with the same index in the input.

    return train_set, valid_set, test_set


if __name__ == '__main__':
    train_set, val_set, test_set = load_data('mnist.pkl.gz')

    train_x, train_y = train_set
    val_x, val_y = val_set
    test_x, test_y = test_set
    
    print(train_x.shape)
    print(train_y.shape)
    
    for i in range(100):
        samp_img = train_x[i].reshape((28, 28))
        scipy.misc.imsave('test'+str(i)+'.jpg', samp_img)
        print(train_y[i])

    mean_img = train_x.mean(1)
    print(train_x)
    print(np.sum(train_x <= 0.1))
    print(np.sum(train_x >= 0.9))
    print(mean_img.shape)


    # for eigendecomposition 
    # check http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html 


NameError: name '__file__' is not defined

In [5]:
import six.moves.cPickle as pickle
import gzip
import os
import numpy as np
#import scipy.misc
from PIL import Image

def load_data(dataset):
    ''' Loads the dataset

    :type dataset: string
    :param dataset: the path to the dataset (here MNIST)
    
    copied from http://deeplearning.net/ and revised by hchoi
    '''

    # Download the MNIST dataset if it is not present
    data_dir, data_file = os.path.split(dataset)
    if data_dir == "" and not os.path.isfile(dataset):
        # Check if dataset is in the data directory.
        new_path = os.path.join(
            os.path.split(__file__)[0],
            dataset
        )
        if os.path.isfile(new_path) or data_file == 'mnist.pkl.gz':
            dataset = new_path

    if (not os.path.isfile(dataset)) and data_file == 'mnist.pkl.gz':
        from six.moves import urllib
        origin = (
            'http://www.iro.umontreal.ca/~lisa/deep/data/mnist/mnist.pkl.gz'
        )
        print('Downloading data from %s' % origin)
        urllib.request.urlretrieve(origin, dataset)

    print('... loading data')

    # Load the dataset
    with gzip.open(dataset, 'rb') as f:
        try:
            train_set, valid_set, test_set = pickle.load(f, encoding='latin1')
        except:
            train_set, valid_set, test_set = pickle.load(f)
    # train_set, valid_set, test_set format: tuple(input, target)
    # input is a numpy.ndarray of 2 dimensions (a matrix)
    # where each row corresponds to an example. target is a
    # numpy.ndarray of 1 dimension (vector) that has the same length as
    # the number of rows in the input. It should give the target
    # to the example with the same index in the input.

    return train_set, valid_set, test_set


if __name__ == '__main__':
    train_set, val_set, test_set = load_data('mnist.pkl.gz')

    train_x, train_y = train_set
    val_x, val_y = val_set
    test_x, test_y = test_set
    
    print(train_x.shape)
    print(train_y.shape)
    
    for i in range(100):
        tmp_img = train_x[i].reshape((28,28))*255.9
        samp_img = Image.fromarray(tmp_img.astype(np.uint8))
        samp_img.save('test'+str(i)+'.jpg')
        print(train_y[i])

    mean_img = train_x.mean(1)
    print(train_x)
    print(np.sum(train_x <= 0.1))
    print(np.sum(train_x >= 0.9))
    print(mean_img.shape)

    cov = np.cov(train_x.T)
    print(cov)
    print(cov.shape)
    # for eigendecomposition 
    # check http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html 
    
    
    

... loading data
(50000, 784)
(50000,)
5
0
4
1
9
2
1
3
1
4
3
5
3
6
1
7
2
8
6
9
4
0
9
1
1
2
4
3
2
7
3
8
6
9
0
5
6
0
7
6
1
8
7
9
3
9
8
5
9
3
3
0
7
4
9
8
0
9
4
1
4
4
6
0
4
5
6
1
0
0
1
7
1
6
3
0
2
1
1
7
9
0
2
6
7
8
3
9
0
4
6
7
4
6
8
0
7
8
3
1
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
32362898
3423594
(50000,)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(784, 784)


In [33]:
train_x.shape

(50000, 784)

In [37]:
cov[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [7]:
import numpy

eig = numpy.linalg.eig

matrix = numpy.matrix
testmatrix = matrix([[1,2,3],[5,3,4],[7,2,3]])

print(eig(testmatrix)) #Eigenvalue와 Eigenvector가 모두 나온다

#print eig(testmatrix)[0] #Eigenvalue 부분을 출력한다

#print eig(testmatrix)[1] #

(array([ 9.46793786, -2.70243651,  0.23449865]), matrix([[-0.3820937 , -0.63380443,  0.02072161],
        [-0.68142297,  0.01324033, -0.83430396],
        [-0.62423324,  0.77338001,  0.55091517]]))


In [12]:
import torch
import torchvision.transforms as trans
from skimage import io
img = io.imread("test1.jpg")

t = trans.ToTensor()(img)
t.shape

torch.Size([1, 28, 28])

In [28]:
t = t.squeeze()
eig(t)[0]


array([ 6.8018169e+00+0.j        ,  3.1117575e+00+0.j        ,
       -3.0743828e+00+0.4562579j , -3.0743828e+00-0.4562579j ,
       -1.1498514e+00+0.22631443j, -1.1498514e+00-0.22631443j,
        1.1139513e+00+0.j        ,  4.2714974e-01+0.17521973j,
        4.2714974e-01-0.17521973j, -3.3177635e-01+0.j        ,
        1.0158062e-01+0.23561177j,  1.0158062e-01-0.23561177j,
       -2.1664175e-01+0.j        , -6.6751190e-02+0.1450425j ,
       -6.6751190e-02-0.1450425j , -9.4343744e-02+0.j        ,
        4.2454530e-02+0.03980229j,  4.2454530e-02-0.03980229j,
        3.3005942e-02+0.j        , -3.5904672e-02+0.j        ,
        2.3563781e-03+0.j        , -3.2606615e-05+0.00112663j,
       -3.2606615e-05-0.00112663j, -1.1221992e-02+0.j        ,
        0.0000000e+00+0.j        ,  0.0000000e+00+0.j        ,
        0.0000000e+00+0.j        ,  0.0000000e+00+0.j        ],
      dtype=complex64)

In [32]:
eig(t)[1][0]

array([-0.00621462+0.j        ,  0.00146372+0.j        ,
        0.00125507+0.00130533j,  0.00125507-0.00130533j,
        0.00159386+0.00668807j,  0.00159386-0.00668807j,
       -0.01001261+0.j        ,  0.01931077-0.00411443j,
        0.01931077+0.00411443j,  0.01968382+0.j        ,
        0.04235825-0.00492497j,  0.04235825+0.00492497j,
       -0.05682964+0.j        ,  0.04977224+0.04027113j,
        0.04977224-0.04027113j, -0.05250446+0.j        ,
        0.1161285 -0.00825123j,  0.1161285 +0.00825123j,
       -0.16564608+0.j        , -0.07794531+0.j        ,
       -0.4878216 +0.j        , -0.17871699+0.22852409j,
       -0.17871699-0.22852409j,  0.02557716+0.j        ,
        0.        +0.j        ,  0.        +0.j        ,
        0.        +0.j        ,  0.        +0.j        ], dtype=complex64)