In [1]:
import numpy as np
import tensorflow as tf

print("PACKAGES LOADED")
print(" Current tf version %s" % (tf.__version__))

PACKAGES LOADED
 Current tf version 2.4.0


In [8]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

sess = tf.Session()
print("open session")

open session


# session.run 사용하기

In [10]:
def print_tf(x):
    print("TYPE IS\n %s"%(type(x)))
    print("VALUE IS\n %s" %(x))
    
hello = tf.constant("HELLO. IT's ME.")
print_tf(hello)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_1:0", shape=(), dtype=string)


In [12]:
hello_out = sess.run(hello) # session에서 run을 시켜주는 구나
print_tf(hello_out)

TYPE IS
 <class 'bytes'>
VALUE IS
 b"HELLO. IT's ME."


# session.run 사용하기2

In [16]:
a = tf.constant(1.5)
print_tf(a)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_5:0", shape=(), dtype=float32)


In [17]:
a_out = sess.run(a)
print_tf(a_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 1.5


# session.run 사용하기3

In [20]:
a = tf.constant(1.5)
b = tf.constant(2.5)
a_plus_b = tf.add(a,b)

# 출력
sess.run(a_plus_b)

4.0

# 정리: sess.run 되기 이전까지의 값들이 tensorflow 내에서 연산이 되고,


가장 윗단에 있는 내용을 sess.run()으로 읽어오면 되는 구조이다.

이러한 구조를 computational graph라고 한다.

# session.run 사용하기4
- variable은 변하는 값
- constant는 고정값

In [31]:
weight = tf.Variable(tf.random_normal([5,2], stddev = 0.1))
print_tf(weight)

# variable에 대한 초기값을 주기 (필수적인 코드임)
init = tf.global_variables_initializer()
sess.run(init)

# 호출
sess.run(weight)

TYPE IS
 <class 'tensorflow.python.ops.variables.RefVariable'>
VALUE IS
 <tf.Variable 'Variable_10:0' shape=(5, 2) dtype=float32_ref>


array([[ 0.02050998, -0.05229034],
       [-0.09439101, -0.02783136],
       [ 0.0171297 , -0.06991579],
       [ 0.149626  , -0.05785697],
       [ 0.14225434,  0.15305503]], dtype=float32)

# Placeholders

집어넣는 것이라고 설명해주심

In [37]:
x = tf.placeholder(tf.float32, [None,5])

oper = tf.matmul(x,weight) # oper 선언
print_tf(oper)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("MatMul_1:0", shape=(?, 2), dtype=float32)


In [47]:
data = np.random.rand(3,5)
oper_out = sess.run(oper, feed_dict= {x: data}) # x는 반드시 ?*5의 형태임.
print_tf(oper_out)

# shape
oper_out.shape

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[ 0.10673143  0.01813232]
 [ 0.16035666 -0.12747023]
 [ 0.128998    0.05754524]]


(3, 2)

# Placeholder 연습

In [58]:
# weight 선언
weight = tf.Variable(tf.random_normal([6,2], stddev= 0.01))
init = tf.global_variables_initializer()
sess.run(init)
sess.run(weight)

# oper 만들기
x = tf.placeholder(tf.float32, [None, 6])
oper = tf.matmul(x,weight)

# feed_dict 사용하기
data = np.random.rand(5,6)
sess.run(oper, feed_dict= {x:data})

array([[-0.03025647,  0.01060422],
       [-0.00848227,  0.01295012],
       [-0.01490594, -0.00731708],
       [-0.00751351, -0.00682406],
       [-0.01315625, -0.00209675]], dtype=float32)