In [2]:
import numpy as np
X = np.array([[0,0,1,1],[0,1,0,1]])  # 2*4 형상
Y = np.array([[0,1,1,0]])        # 1*4 형상
print('X.shape={}, Y.shape={}'.format(X.shape,Y.shape))
print(X) #입력층
print(Y) #클래스레이블


X.shape=(2, 4), Y.shape=(1, 4)
[[0 0 1 1]
 [0 1 0 1]]
[[0 1 1 0]]


In [9]:
#가중치 행렬의 형상 구현
n_x = X.shape[0]
n_y = Y.shape[0]
n_h = 3
np.random.seed(1)
W1 = 2*np.random.random((n_h,n_x))-1  # 3*2 형상   --> w1 x0 = 3*4형상
W2 = 2*np.random.random((n_y,n_h))-1  # 1*3 형상   --> w2 x1 = 1*4 형상 --> yhat으로 Y와 비교.
print("W1: {}".format(W1))
print("W2: {}".format(W2))


W1: [[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]
W2: [[-0.62747958 -0.30887855 -0.20646505]]


In [11]:
W1.shape

(3, 2)