In [1]:
import torch
import torch.nn as nn
import torch.optim as optim


import torchvision
import torchvision.datasets as dsets # 데이터셋 (Mnist, Cifar 등)
import torchvision.transforms as transforms

from torch.utils.data import Dataset, DataLoader # Custom data 및 Dataloader


In [2]:
# Dataset download
mnist_train = dsets.MNIST(root = "MNIST_data/", train = True, transform=transforms.ToTensor(), download = True)
mnist_test = dsets.MNIST(root = "MNIST_data/", train = False, transform=transforms.ToTensor(), download = True)

fashion_train = dsets.FashionMNIST(root = "Fashion_data", train = True, transform=transforms.ToTensor(), download= True)
fashion_test = dsets.FashionMNIST(root = "Fashion_data", train = False, transform=transforms.ToTensor(), download= True)



# 데이터저장 (클래스번호/사진번호)

### Train
- 클래스당 2000개씩

In [3]:
# mnist 저장.
num_imags = [1]*21
for sample in mnist_train:
    img, label = sample
    if num_imags[label] > 2000:
        continue
    
    # tensor를 이미지로 변환
    PIL_img = transforms.ToPILImage()(img)
    print(PIL_img)
    # 클래스번호/사진번호로 저장
    PIL_img.save("./train/%d/%d.jpeg"%(label,num_imags[label]))
    # 카운트
    num_imags[label] += 1
    
# fashion_mnist 저장.
for sample in fashion_train:
    img,label = sample
    label += 10
    if num_imags[label] > 2000:
        continue
    
    PIL = transforms.ToPILImage()(img)
    PIL.save('./train/%d/%d.jpeg'%(label, num_imags[label]))
    num_imags[label] += 1



<PIL.Image.Image image mode=L size=28x28 at 0x7FCE87B17C70>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1580>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1580>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE89993CA0>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1580>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1580>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1580>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1580>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28

<PIL.Image.Image image mode=L size=28x28 at 0x7FCE9031AB20>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1580>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1580>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE9031AB20>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1580>
<PIL.Image.Image image mode=L size=28x28

<PIL.Image.Image image mode=L size=28x28 at 0x7FCE9032AFD0>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE9032A6D0>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE9032AFD0>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE9031AB20>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE9032A6D0>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE9031AB20>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE9032A6D0>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE9031AB20>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1580>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1580>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE9032A6D0>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE9032AFD0>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE9032A6D0>
<PIL.Image.Image image mode=L size=28x28

<PIL.Image.Image image mode=L size=28x28 at 0x7FCE9032AFD0>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1580>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1580>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE9032A6D0>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1580>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1580>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1F10>
<PIL.Image.Image image mode=L size=28x28 at 0x7FCE899A1E80>
<PIL.Image.Image image mode=L size=28x28

KeyboardInterrupt: 

# image Folder 사용하기
폴더 형태로 있으면 사용 가능하구나!

In [ ]:
from torchvision.datasets import ImageFolder

train_dataset = ImageFolder(root='./train', transform= transforms.ToTensor())
temp_loader = DataLoader(train_dataset, batch_size=128, shuffle=True, num_workers=4)



In [ ]:

orig_set = train_dataset  # your dataset
n = len(orig_set)  # total number of examples
n_test = int(0.1 * n)  # take ~10% for test
test_set = torch.utils.data.Subset(orig_set, range(n_test))  # take first 10%
train_set = torch.utils.data.Subset(orig_set, range(n_test, n))

In [ ]:
train_loader = DataLoader(train_set, batch_size= 100, shuffle = True, drop_last= True)
test_loader = DataLoader(test_set, batch_size= 100, shuffle = False, drop_last= False)



In [47]:
for X,Y in train_loader:
    break

In [49]:
X.shape

torch.Size([100, 3, 28, 28])

In [50]:
Y

tensor([18, 17, 17, 20, 19, 20, 17,  1, 17, 20, 19, 12, 12, 14, 17,  1, 16, 15,
        14, 17,  6, 17,  1, 17, 17, 20, 20, 18, 15, 20, 16, 15, 20,  2, 10, 18,
        20, 19, 12, 19, 14,  1,  3, 16, 18,  4, 20, 19, 18, 19, 20, 16, 17, 14,
         1, 17, 20, 18, 15, 19,  1,  1, 16, 20, 20, 20, 17, 18, 15, 15, 16, 19,
         1, 18,  1,  1, 17, 18, 19, 12, 18, 16, 14,  1, 20,  1,  1, 17, 14,  1,
        12, 19, 16, 15, 18, 19, 15, 16, 18, 19])

### Test
- 클래스당 1000개씩

In [ ]:
# Test
test_images = [1]*21
for sample in mnist_test:
    img, label = sample
    if test_images[label] > 1000:
        continue
    
    PIL = transforms.ToPILImage()(img)
    PIL.save("./test/%d/%d.jpeg"%(label, test_images[label]))
    test_images[label] += 1

for sample in fashion_test:
    img, label = sample
    label += 10
    if test_images[label] > 1000:
        continue
    PIL2 = transforms.ToPILImage()(img)
    PIL2.save("./test/%d/%d.jpeg"%(label, test_images[label]))
    test_images[label] += 1

print(test_images)


# Custom DataSet

In [27]:
import os
from skimage import io
 

    
# dataset만들기
class CustomDataset(Dataset):
    def __init__(self, root_dir, transform = None):
        
        self.root_dir = root_dir
        self.transform = transform
        self.x = []
        self.y = []
        
        # 디렉토리 (20개)
        for i in range(20):
            init_path = self.root_dir + "/" + str(i) + "/"

            # 디렉토리 내부(폴더당 2000개씩)
            for j in range(len(os.listdir(init_path))):
                img_path = init_path + os.listdir(init_path)[j] #이미지의 Path
                img = io.imread(img_path) #실제 이미지 읽어오기
                
                # 추가
                self.x.append(img)
                self.y.append([i])
                
    def __len__(self):
        return len(self.x)
    
    def __getitem__(self,idx):
        
        x = self.x[idx]
        y = self.y[idx]
        
        if self.transform:
            x = transforms.ToPILImage()(x) #이미지로 변환
            x = self.transform(x)
#             x = transforms.ToTensor()(x) #다시 Tensor로 변환. (아래 trans에도 있는 구문이기에, 여기서는 주석처리)
            
        x = torch.FloatTensor(x)
        y = torch.FloatTensor(y)

        return x,y
        
        


# transform
trans = transforms.Compose([
#         transforms.Resize((224,224)),
        transforms.ToTensor(),    
])

dataset = CustomDataset(root_dir = "./train", transform = trans )
train_loader = DataLoader(dataset=dataset, batch_size = 100, shuffle = True, drop_last= True)




# 정규화를 위한 함수

In [28]:
# function for mean & std
def get_mean_std(loader):
    mu = 0
    mu_square = 0
    std = 0
    for sample in loader:
        X,Y = sample

        mu += torch.mean(X, dim = [0,2,3])
        mu_square += torch.mean(X**2, dim = [0,2,3])
        std += torch.std(X, dim = [0,2,3])

    mu /= len(loader)
    mu_square /= len(loader)
    std = (mu_square - mu**2)**0.5 # E[X**2] - {E[X]}**2
    return mu, std



mu, std = get_mean_std(train_loader)
print(mu, std)
    

tensor([0.2127]) tensor([0.3378])


# 위 값을 가지고, 다시 dataset 호출하기

In [30]:
trans = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.2127),(0.3378))
])

train_dataset = CustomDataset(root_dir = "./train", transform = trans)
train_loader = DataLoader(dataset=train_dataset, batch_size = 100, shuffle = True, drop_last= True)


In [31]:
get_mean_std(train_loader)

(tensor([6.5138e-05]), tensor([1.0000]))

In [32]:
test_dataset = CustomDataset(root_dir = "./test", transform = trans)
test_loader = DataLoader(dataset=test_dataset, batch_size = 100, shuffle = False, drop_last= False)

In [33]:
get_mean_std(test_loader)

(tensor([0.0049]), tensor([1.0009]))

# Model 이랑 Test 돌려보기

In [4]:
#step2) device
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.manual_seed(777)
if device == "cuda":
    torch.cuda.manual_seed_all(777)

#step3) hyper-parameter
learning_rate = 0.001
batch_size = 100
training_epoch = 10


#step4) dataset & dataloader (위에서 이미 해결)


#step5) 모델링
class CNN(nn.Module):
    def __init__(self,num_classes):
        super(CNN,self).__init__()
        
        # 1*28*28
        self.layer1 = nn.Sequential(
            nn.Conv2d(1,128,3, padding= 1), 
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(2),


        )
        
        # 128*14*14
        self.layer2 = nn.Sequential(
            nn.Conv2d(128,128*2,1), 
            nn.BatchNorm2d(128*2),
            nn.ReLU(),
            nn.MaxPool2d(2),
        )
        
        # 256*7*7
        self.layer3 = nn.Sequential( 
            nn.Conv2d(256,256*2,3, groups = 256, padding = 1),
            nn.BatchNorm2d(256*2),
            nn.ReLU(),
            nn.MaxPool2d(2),
        )
        
        # 512*3*3
        self.layer4 = nn.Sequential(
            nn.Conv2d(512,512*2,1),
            nn.BatchNorm2d(512*2),
            nn.ReLU(),
            nn.MaxPool2d(2),
        )
        
        # 1024*1*1
        self.layer5 = nn.Sequential(
            nn.Linear(1024,512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(0.5),

            
            nn.Linear(512,num_classes)
        )
        
    def forward(self,x):
        out = self.layer1(x)
        
        out = self.layer2(out)
        
        out = self.layer3(out)
        
        out = self.layer4(out)
        
        out = out.view(out.size(0), -1)
        
        out = self.layer5(out)

        return out
    
    def initalize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode = "fan_out", nonlinearity= "relu")
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight,1)
                nn.init.constant_(m.bias,0)
            elif isinstance(m, nn.Linear):
                nn.init.normal_(m.weight, 0, 0.01)
                nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm1d):
                nn.init.constant_(m.weight,1)
                nn.init.constant_(m.bias,0)
        
        

model = CNN(num_classes = 20).to(device)
model.initalize_weights()

test = torch.Tensor(2,1,28,28).to(device)
model(test)



tensor([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]],
       grad_fn=<AddmmBackward>)

In [83]:
#step6) loss & optim
criterion = nn.CrossEntropyLoss().to(device)
optimizer = optim.Adam(model.parameters(), lr = learning_rate)



In [84]:
# loss 그래프 그리기
import visdom
vis = visdom.Visdom()

def loss_tracker(loss_plt, loss_value, num):
    vis.line(X = num,
             Y = loss_value,
             win = loss_plt,
             update = "append")
    
loss_plt = vis.line(Y = torch.Tensor(1).zero_(), opts = dict(title = "loss_tracker",
                                                             legend = ["loss"],
                                                             showlegend = True))


Setting up a new session...


In [89]:
#step7) train
iteration = len(train_loader)
model.train()

for epoch in range(training_epoch):
    loss = 0
    correct = 0
    for sample in train_loader:
        optimizer.zero_grad()
        
        X,Y = sample
        X = X.to(device)
        Y = Y.to(device)
        Y = torch.squeeze(Y) # 채널 맞추기
        Y = Y.long() # type 맞추기
        
        # forward & backward & optim
        hypothesis = model(X)
        cost = criterion(hypothesis, Y)
        cost.backward()
        optimizer.step()
        
        #calculate
        loss += cost.item()
        correct += (torch.argmax(hypothesis, dim = 1) == Y).float().sum()
    
    loss /= iteration
    acc = correct / (batch_size * iteration)
    print("[Epoch {:04d}, loss = {:.4f}, acc = {:.2f}]%".format(epoch, loss, acc*100))
    
    # 그래프 그리기 및 weight 저장하기.
    loss_tracker(loss_plt, torch.FloatTensor([loss]), torch.FloatTensor([epoch]))
    torch.save(model.state_dict(), "./hw5_weight/%d_%d.pth"%(epoch+1,int(acc*100)))
    
    

[Epoch 0000, loss = 0.2306, acc = 91.62]%
[Epoch 0001, loss = 0.1903, acc = 92.96]%
[Epoch 0002, loss = 0.1642, acc = 93.89]%
[Epoch 0003, loss = 0.1420, acc = 94.69]%
[Epoch 0004, loss = 0.1270, acc = 95.24]%
[Epoch 0005, loss = 0.1146, acc = 95.64]%
[Epoch 0006, loss = 0.0995, acc = 96.24]%
[Epoch 0007, loss = 0.0872, acc = 96.67]%
[Epoch 0008, loss = 0.0837, acc = 96.79]%
[Epoch 0009, loss = 0.0724, acc = 97.24]%


In [100]:
#step8) test

with torch.no_grad():
    model.eval()
    loss = 0
    correct = 0
    iteration = len(test_loader)

    for sample in test_loader:
        X, Y = sample
        X = X.to(device)
        Y = torch.squeeze(Y)
        Y = Y.long()
        
        hypothesis = model(X)
        cost = criterion(hypothesis, Y)
        
        # calculate
        loss += cost.item()
        correct += (torch.argmax(hypothesis, dim = 1) == Y).float().sum()
    
    
    loss /= iteration
    acc = correct / (iteration*batch_size)
    print("[Test] loss = {:.4f}, acc = {:.2f}%".format(loss, acc*100))
        
        
        


[Test] loss = 8.9370, acc = 5.05%


# Depthwise_separable_conv에서 
depth_wise 채널 잡는게 조금 신기
--> 인풋채널에 대해서, 몇개의 커널set을 사용할것인지 중요

In [ ]:
class depthwise_separable_conv(nn.Module):
    def __init__(self, nin, kernels_per_layer, nout):
        super(depthwise_separable_conv, self).__init__()
        self.depthwise = nn.Conv2d(nin, nin * kernels_per_layer, kernel_size=3, padding=1, groups=nin)
        self.pointwise = nn.Conv2d(nin * kernels_per_layer, nout, kernel_size=1)

    def forward(self, x):
        out = self.depthwise(x)
        out = self.pointwise(out)
        return out